branches:
  - master

language: php

php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

before_script:
  - mysql -e 'CREATE DATABASE `order-pay-test` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci'
  - mysql -u root -e "CREATE USER 'root'@'localhost' IDENTIFIED BY ''"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost'"

script:
  - phpunit -c .
